name: Push to Deta Space
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  push-to-space:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push to Deta Space
        uses: neobrains/space-deployment-github-action@v0.3
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          project_id: ${{ secrets.PROJECT_ID }}
          space_push: true